-- ============================================================================
-- ChronoSparkSolutions — A Software Company
-- © 2026 ChronoSparkSolutions. All rights reserved.
--
-- Project     : F2H Fresh
-- File        : 007-missing-operational-tables.sql
-- Description : Second drift pass. Creates the operational tables that admin
--               endpoints query but that were never present in the live
--               database, and reconciles packaging_types with the column names
--               the packaging CRUD writes.
--
--               Found by sweeping every parameterless GET endpoint against a
--               build of the current source and collecting the SQL failures.
-- ============================================================================

BEGIN;

-- ── Production planning (admin → Production → Planning) ─────────────────────
CREATE TABLE IF NOT EXISTS production_plans (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_id     varchar(40) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
  branch_id         varchar(30),
  warehouse_id      varchar(30),
  variant_id        varchar(30) NOT NULL,
  planned_quantity  numeric(12,2) NOT NULL DEFAULT 0,
  produced_quantity numeric(12,2) NOT NULL DEFAULT 0,
  product_id        varchar(30),
  planned_date      date          NOT NULL DEFAULT CURRENT_DATE,
  production_status varchar(20)   DEFAULT 'planned',
  priority          varchar(20)   DEFAULT 'normal',
  notes             text,
  created_by        varchar(30),
  updated_by        varchar(30),
  created_at        timestamptz   DEFAULT now(),
  updated_at        timestamptz   DEFAULT now(),
  deleted_at        timestamp
);

CREATE INDEX IF NOT EXISTS production_plans_date_idx   ON production_plans (planned_date DESC);
CREATE INDEX IF NOT EXISTS production_plans_status_idx ON production_plans (production_status);

-- ── Vendors and goods intake (admin → Vendors, Warehouse → Intake) ──────────
CREATE TABLE IF NOT EXISTS vendors (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id      varchar(30)  NOT NULL UNIQUE,
  name           varchar(200) NOT NULL,
  contact_person varchar(150),
  phone          varchar(20),
  email          varchar(150),
  gst_number     varchar(20),
  address        text,
  city           varchar(100),
  state          varchar(100),
  pincode        varchar(10),
  payment_terms  varchar(100),
  is_active      boolean      DEFAULT true,
  notes          text,
  created_by     varchar(30),
  updated_by     varchar(30),
  created_at     timestamptz  DEFAULT now(),
  updated_at     timestamptz  DEFAULT now(),
  deleted_at     timestamp
);

CREATE TABLE IF NOT EXISTS vendor_intakes (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intake_id      varchar(40) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
  vendor_id      varchar(30),
  warehouse_id   varchar(30),
  product_id     varchar(30),
  variant_id     varchar(30),
  batch_id       varchar(40),
  quantity       numeric(12,2) NOT NULL DEFAULT 0,
  unit_type      varchar(20)   DEFAULT 'pcs',
  unit_cost      numeric(12,2) DEFAULT 0,
  total_cost     numeric(12,2) DEFAULT 0,
  quality_status varchar(20)   DEFAULT 'pending',
  intake_status  varchar(20)   DEFAULT 'pending',
  vehicle_number varchar(30),
  received_by    varchar(30),
  received_at    timestamptz,
  notes          text,
  created_by     varchar(30),
  created_at     timestamptz   DEFAULT now(),
  updated_at     timestamptz   DEFAULT now(),
  deleted_at     timestamp
);

CREATE INDEX IF NOT EXISTS vendor_intakes_vendor_idx    ON vendor_intakes (vendor_id);
CREATE INDEX IF NOT EXISTS vendor_intakes_warehouse_idx ON vendor_intakes (warehouse_id);

-- ── Per-day subscription overrides (admin → Subscriptions → Overrides) ──────
CREATE TABLE IF NOT EXISTS subscription_overrides (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id      varchar(30) NOT NULL,
  subscription_item_id varchar(30),
  override_date        date        NOT NULL,
  override_type        varchar(30) DEFAULT 'extra',
  m_quantity           numeric(10,2) DEFAULT 0,
  e_quantity           numeric(10,2) DEFAULT 0,
  is_paid              boolean     DEFAULT false,
  notes                text,
  created_by           varchar(30),
  created_at           timestamptz DEFAULT now(),
  updated_at           timestamptz DEFAULT now(),
  deleted_at           timestamp,
  CONSTRAINT subscription_overrides_uniq
    UNIQUE (subscription_item_id, override_date, override_type)
);

CREATE INDEX IF NOT EXISTS subscription_overrides_sub_idx  ON subscription_overrides (subscription_id);
CREATE INDEX IF NOT EXISTS subscription_overrides_date_idx ON subscription_overrides (override_date);

-- ── Pre-aggregated demand calendar (admin → Subscriptions → Calendar) ───────
-- Rebuilt in bulk by CalendarRepository.rebuildRange, which upserts on the
-- (date, branch, zone, variant) grain — hence the matching unique key.
CREATE TABLE IF NOT EXISTS subscription_calendar_cache (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calendar_date             date        NOT NULL,
  branch_id                 varchar(30) NOT NULL DEFAULT 'ALL',
  zone_id                   varchar(30) NOT NULL DEFAULT 'ALL',
  product_variant_id        varchar(30) NOT NULL,
  total_m_qty               numeric(12,2) DEFAULT 0,
  total_e_qty               numeric(12,2) DEFAULT 0,
  total_pause_count         integer       DEFAULT 0,
  total_extra_count         integer       DEFAULT 0,
  total_custom_count        integer       DEFAULT 0,
  active_subscription_count integer       DEFAULT 0,
  estimated_routes          integer       DEFAULT 0,
  generated_at              timestamptz   DEFAULT now(),
  CONSTRAINT subscription_calendar_cache_uniq
    UNIQUE (calendar_date, branch_id, zone_id, product_variant_id)
);

CREATE INDEX IF NOT EXISTS scc_date_idx ON subscription_calendar_cache (calendar_date);

-- ── Wallet balance lookup ---------------------------------------------------
-- The customer tables join a `customer_wallet_balances` relation; the balance
-- itself lives on customers, so expose it as a view rather than duplicating it.
-- deleted_at is projected because DataService appends a soft-delete predicate
-- to every relation it queries.
CREATE OR REPLACE VIEW customer_wallet_balances AS
  SELECT
    customer_id,
    COALESCE(wallet_balance, 0) AS wallet_balance,
    updated_at,
    deleted_at
  FROM customers;

-- ── packaging_types: the CRUD writes capacity/unit/is_returnable/status ─────
ALTER TABLE production_plans ADD COLUMN IF NOT EXISTS product_id varchar(30);

ALTER TABLE packaging_types ADD COLUMN IF NOT EXISTS capacity      numeric(10,2) DEFAULT 1;
ALTER TABLE packaging_types ADD COLUMN IF NOT EXISTS unit          varchar(20)   DEFAULT 'PCS';
ALTER TABLE packaging_types ADD COLUMN IF NOT EXISTS is_returnable boolean       DEFAULT true;
ALTER TABLE packaging_types ADD COLUMN IF NOT EXISTS status        varchar(20)   DEFAULT 'active';

UPDATE packaging_types
   SET capacity = COALESCE(capacity, unit_value, 1),
       unit     = COALESCE(unit, unit_type, 'PCS'),
       status   = COALESCE(status, CASE WHEN is_active THEN 'active' ELSE 'inactive' END);

-- ── management_staff is soft-deleted like every other entity ───────────────
ALTER TABLE management_staff ADD COLUMN IF NOT EXISTS deleted_at timestamp;

COMMIT;
