-- ============================================================================
-- ChronoSparkSolutions — A Software Company
-- © 2026 ChronoSparkSolutions. All rights reserved.
--
-- Project     : F2H Fresh
-- File        : 007-missing-operational-tables.sql
-- Description : Second drift pass. Creates the operational tables that admin
--               endpoints query but that were never present in the live
--               database.
--
--               Found by sweeping every parameterless GET endpoint against a
--               build of the current source and collecting the SQL failures.
-- ============================================================================

BEGIN;

-- ── Production planning (admin → Production → Planning) ─────────────────────
CREATE TABLE IF NOT EXISTS production_plans (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_id     varchar(40) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
  branch_id         varchar(30),
  warehouse_id      varchar(30),
  variant_id        varchar(30) NOT NULL,
  planned_quantity  numeric(12,2) NOT NULL DEFAULT 0,
  produced_quantity numeric(12,2) NOT NULL DEFAULT 0,
  product_id        varchar(30),
  planned_date      date          NOT NULL DEFAULT CURRENT_DATE,
  production_status varchar(20)   DEFAULT 'planned',
  priority          varchar(20)   DEFAULT 'normal',
  notes             text,
  created_by        varchar(30),
  updated_by        varchar(30),
  created_at        timestamptz   DEFAULT now(),
  updated_at        timestamptz   DEFAULT now(),
  deleted_at        timestamp
);

CREATE INDEX IF NOT EXISTS production_plans_date_idx   ON production_plans (planned_date DESC);
CREATE INDEX IF NOT EXISTS production_plans_status_idx ON production_plans (production_status);
-- ── Wallet balance lookup ---------------------------------------------------
-- The customer tables join a `customer_wallet_balances` relation; the balance
-- itself lives on customers, so expose it as a view rather than duplicating it.
-- deleted_at is projected because DataService appends a soft-delete predicate
-- to every relation it queries.
CREATE OR REPLACE VIEW customer_wallet_balances AS
  SELECT
    customer_id,
    COALESCE(wallet_balance, 0) AS wallet_balance,
    updated_at,
    deleted_at
  FROM customers;

-- ── packaging_types: the CRUD writes capacity/unit/is_returnable/status ─────
ALTER TABLE production_plans ADD COLUMN IF NOT EXISTS product_id varchar(30);

ALTER TABLE packaging_types ADD COLUMN IF NOT EXISTS capacity      numeric(10,2) DEFAULT 1;
ALTER TABLE packaging_types ADD COLUMN IF NOT EXISTS unit          varchar(20)   DEFAULT 'PCS';
ALTER TABLE packaging_types ADD COLUMN IF NOT EXISTS is_returnable boolean       DEFAULT true;
ALTER TABLE packaging_types ADD COLUMN IF NOT EXISTS status        varchar(20)   DEFAULT 'active';

UPDATE packaging_types
   SET capacity = COALESCE(capacity, unit_value, 1),
       unit     = COALESCE(unit, unit_type, 'PCS'),
       status   = COALESCE(status, CASE WHEN is_active THEN 'active' ELSE 'inactive' END);

-- ── management_staff is soft-deleted like every other entity ───────────────
ALTER TABLE management_staff ADD COLUMN IF NOT EXISTS deleted_at timestamp;

COMMIT;
