-- ============================================================================
-- ChronoSparkSolutions — A Software Company
-- © 2026 ChronoSparkSolutions. All rights reserved.
--
-- Project     : F2H Fresh
-- File        : 008-subscription-config-tables.sql
-- Description : Storage for admin → Catalog → Subscription Config. The service
--               (CatalogSubscriptionConfigService) was written against these
--               six relations but they were never created, so every tab on
--               that page failed. Column names and the ON CONFLICT targets
--               below mirror the service's statements exactly.
-- ============================================================================

BEGIN;

-- ── Billing rules (single 'default' row) ───────────────────────────────────
CREATE TABLE IF NOT EXISTS catalog_subscription_config (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_key                varchar(50)  NOT NULL UNIQUE DEFAULT 'default',
  pauses_allowed            boolean      NOT NULL DEFAULT true,
  skips_allowed             boolean      NOT NULL DEFAULT true,
  modifications_allowed     boolean      NOT NULL DEFAULT true,
  auto_renew_allowed        boolean      NOT NULL DEFAULT true,
  billing_cycles            jsonb        NOT NULL DEFAULT '["monthly"]'::jsonb,
  default_billing_cycle     varchar(20)  NOT NULL DEFAULT 'monthly',
  min_subscription_days     integer      NOT NULL DEFAULT 7,
  max_pause_days_per_request integer     NOT NULL DEFAULT 14,
  max_pauses_per_month      integer      NOT NULL DEFAULT 2,
  max_pauses_per_year       integer      NOT NULL DEFAULT 12,
  pause_notice_hours        integer      NOT NULL DEFAULT 24,
  modification_notice_hours integer      NOT NULL DEFAULT 12,
  billing_cutoff_day        integer      NOT NULL DEFAULT 25,
  renewal_grace_days        integer      NOT NULL DEFAULT 3,
  trial_allowed             boolean      NOT NULL DEFAULT false,
  trial_days                integer      NOT NULL DEFAULT 0,
  admin_notes               text,
  created_by                varchar(30),
  updated_by                varchar(30),
  created_at                timestamptz  DEFAULT now(),
  updated_at                timestamptz  DEFAULT now(),
  deleted_at                timestamp
);

-- ── Global switches. The upsert targets (id), so the singleton row is id = 1.
CREATE TABLE IF NOT EXISTS subscription_global_config (
  id                                  integer     PRIMARY KEY DEFAULT 1,
  subscriptions_enabled               boolean     NOT NULL DEFAULT true,
  pauses_allowed                      boolean     NOT NULL DEFAULT true,
  skips_allowed                       boolean     NOT NULL DEFAULT true,
  modifications_allowed               boolean     NOT NULL DEFAULT true,
  auto_renew_allowed                  boolean     NOT NULL DEFAULT true,
  daily_cutoff_time                   time        DEFAULT '21:00',
  cutoff_timezone                     varchar(50) DEFAULT 'Asia/Kolkata',
  minimum_start_notice_hours          integer     DEFAULT 12,
  reserve_inventory_for_subscriptions boolean     DEFAULT false,
  auto_pause_on_payment_failure       boolean     DEFAULT true,
  created_by                          varchar(30),
  updated_by                          varchar(30),
  created_at                          timestamptz DEFAULT now(),
  updated_at                          timestamptz DEFAULT now(),
  deleted_at                          timestamp,
  CONSTRAINT subscription_global_config_singleton CHECK (id = 1)
);

-- ── Delivery slots, upserted by `code` ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS subscription_delivery_slots (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       varchar(30)  NOT NULL UNIQUE,
  name       varchar(100) NOT NULL,
  start_time time,
  end_time   time,
  is_active  boolean      DEFAULT true,
  created_by varchar(30),
  updated_by varchar(30),
  created_at timestamptz  DEFAULT now(),
  updated_at timestamptz  DEFAULT now(),
  deleted_at timestamp
);

-- ── Per-product subscription rules, upserted by product_id ─────────────────
CREATE TABLE IF NOT EXISTS product_subscription_rules (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id           varchar(30) NOT NULL UNIQUE,
  subscription_allowed boolean     DEFAULT true,
  subscription_only    boolean     DEFAULT false,
  min_quantity         numeric(10,2) DEFAULT 1,
  max_quantity         numeric(10,2) DEFAULT 10,
  quantity_step        numeric(10,2) DEFAULT 1,
  default_quantity     numeric(10,2) DEFAULT 1,
  default_frequency    varchar(20)   DEFAULT 'daily',
  morning_slot_allowed boolean       DEFAULT true,
  evening_slot_allowed boolean       DEFAULT true,
  inventory_reserved   boolean       DEFAULT false,
  is_active            boolean       DEFAULT true,
  created_by           varchar(30),
  updated_by           varchar(30),
  created_at           timestamptz   DEFAULT now(),
  updated_at           timestamptz   DEFAULT now(),
  deleted_at           timestamp
);

CREATE TABLE IF NOT EXISTS product_subscription_frequencies (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_subscription_rule_id bigint NOT NULL
    REFERENCES product_subscription_rules(id) ON DELETE CASCADE,
  frequency_type              varchar(20) NOT NULL,
  interval_days               integer     DEFAULT 1,
  created_by                  varchar(30),
  updated_by                  varchar(30),
  created_at                  timestamptz DEFAULT now(),
  updated_at                  timestamptz DEFAULT now(),
  deleted_at                  timestamp,
  CONSTRAINT product_subscription_frequencies_uniq
    UNIQUE (product_subscription_rule_id, frequency_type)
);

CREATE TABLE IF NOT EXISTS product_subscription_slot_rules (
  id                           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_subscription_rule_id bigint NOT NULL
    REFERENCES product_subscription_rules(id) ON DELETE CASCADE,
  delivery_slot_id             bigint NOT NULL
    REFERENCES subscription_delivery_slots(id) ON DELETE CASCADE,
  created_by                   varchar(30),
  updated_by                   varchar(30),
  created_at                   timestamptz DEFAULT now(),
  updated_at                   timestamptz DEFAULT now(),
  deleted_at                   timestamp,
  CONSTRAINT product_subscription_slot_rules_uniq
    UNIQUE (product_subscription_rule_id, delivery_slot_id)
);

-- ── Seed the singletons so the page loads with defaults rather than empty ──
INSERT INTO catalog_subscription_config (config_key)
VALUES ('default')
ON CONFLICT (config_key) DO NOTHING;

INSERT INTO subscription_global_config (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO subscription_delivery_slots (code, name, start_time, end_time)
VALUES ('morning', 'Morning', '06:00', '10:00'),
       ('evening', 'Evening', '16:00', '20:00')
ON CONFLICT (code) DO NOTHING;

COMMIT;
