-- 007_dispatch_tables_and_management_staff.sql
--
-- Baselines the management_staff table that DatabaseService.createRequiredTables()
-- used to create at application boot, plus the columns it added with
-- ALTER ... IF NOT EXISTS. The dispatch tables this file also created are gone
-- from the live schema and have been removed here.
--
-- Generated from the LIVE database with `pg_dump --schema-only`, not from the
-- TypeScript that created them: the boot code declared foreign keys and a
-- UNIQUE(run_id, product_variant_id) that the live tables do not have, because
-- CREATE TABLE IF NOT EXISTS silently skips a table that already exists. The live
-- shape is the authority.
--
-- Applying this to an environment that already ran the boot code is a no-op.

BEGIN;
CREATE TABLE IF NOT EXISTS public.management_staff (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_id  character varying(30) UNIQUE,
    user_id        character varying(30) NOT NULL,
    branch_id      character varying(30),
    role_id        character varying(30) DEFAULT 'ADMIN',
    user_name      character varying(50),
    department     character varying(100),
    designation    character varying(100),
    is_active      boolean DEFAULT true,
    bio            text,
    gender         character varying(20),
    date_of_birth  date,
    marital_status character varying(30),
    phone          character varying(20),
    alt_phone      character varying(20),
    address_line1  character varying(100),
    address_line2  character varying(100),
    city           character varying(50),
    state          character varying(50),
    postal_code    character varying(20),
    education      character varying(100),
    created_at     timestamptz DEFAULT now(),
    updated_at     timestamptz DEFAULT now(),
    deleted_at     timestamp
);

CREATE INDEX IF NOT EXISTS idx_mgmt_staff_user ON public.management_staff (user_id);

-- Columns the boot code appended to two pre-existing tables.
ALTER TABLE public.product_banner    ADD COLUMN IF NOT EXISTS description       text;
ALTER TABLE public.product_banner    ADD COLUMN IF NOT EXISTS background_color  character varying(50);
ALTER TABLE public.delivery_partners ADD COLUMN IF NOT EXISTS emergency_contact        character varying(150);
ALTER TABLE public.delivery_partners ADD COLUMN IF NOT EXISTS emergency_contact_number character varying(20);
ALTER TABLE public.delivery_partners ADD COLUMN IF NOT EXISTS date_of_birth            date;
ALTER TABLE public.delivery_partners ADD COLUMN IF NOT EXISTS gender                   character varying(20);
ALTER TABLE public.delivery_partners ADD COLUMN IF NOT EXISTS residential_address      text;

COMMIT;
