CREATE TABLE "contact_enquiries" (
  "id" int NOT NULL,
  "enquiry_id" VARCHAR(30) NOT NULL,
  "full_name" VARCHAR(150) NOT NULL,
  "phone" VARCHAR(20) NOT NULL,
  "product_id" VARCHAR(20) DEFAULT NULL,
  "product_name" VARCHAR(150) DEFAULT NULL,
  "quantity" decimal(8,2) NOT NULL DEFAULT '1.00',
  "unit_type" VARCHAR(20) DEFAULT 'litre',
  "address" text NOT NULL,
  "address_line1" VARCHAR(255) DEFAULT NULL,
  "city" VARCHAR(100) DEFAULT NULL,
  "state" VARCHAR(100) DEFAULT NULL,
  "pincode" VARCHAR(10) DEFAULT NULL,
  "map_url" VARCHAR(255) DEFAULT NULL,
  "notes" text,
  "status" VARCHAR(255) NOT NULL DEFAULT 'new',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ,
  "deleted_at" timestamp NULL DEFAULT NULL
);
