-- 011-role-assignments-identity.sql
--
-- `role_assignments.id` is a bigint with no default, so callers had to invent one.
-- The (now-deleted) ADMIN backdoor in users.controller.ts used `Date.now()`:
-- two grants in the same millisecond collided, `ON CONFLICT DO NOTHING` swallowed
-- the second, and a user quietly did not get their role.
--
-- The database owns the key from here. Existing ids are left alone; the identity
-- sequence starts above the current maximum (a Date.now() value, ~1.79e12) so it
-- can never collide with one.
--
-- Also adds the uniqueness the code has always assumed: one active grant of a role
-- per user. Without it, `ON CONFLICT DO NOTHING` on (user_id, role_id) had no
-- constraint to conflict against and duplicates accumulated.

BEGIN;

ALTER TABLE public.role_assignments
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
  pg_get_serial_sequence('public.role_assignments', 'id'),
  GREATEST((SELECT COALESCE(max(id), 0) FROM public.role_assignments), 1) + 1,
  false
);

-- Partial: a soft-deleted grant may coexist with a live one for the same pair.
CREATE UNIQUE INDEX IF NOT EXISTS uq_role_assignments_user_role
  ON public.role_assignments (user_id, role_id)
  WHERE deleted_at IS NULL;

COMMIT;
