-- ============================================================================
-- ChronoSparkSolutions — A Software Company
-- © 2026 ChronoSparkSolutions. All rights reserved.
--
-- Project     : F2H Fresh
-- File        : 017-system-configurations.sql
-- Description : Storage for Admin → Developer → System Configurations (Cron run times,
--               slot cutoffs, delivery charges, discount rules, ordering limits).
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS system_configurations (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_key   varchar(60) NOT NULL UNIQUE,
  category     varchar(40) NOT NULL DEFAULT 'system',
  name         varchar(100) NOT NULL,
  description  text,
  config_data  jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active    boolean NOT NULL DEFAULT true,
  updated_by   varchar(50),
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now(),
  deleted_at   timestamp
);

CREATE INDEX IF NOT EXISTS idx_system_configurations_key ON system_configurations(config_key);
CREATE INDEX IF NOT EXISTS idx_system_configurations_category ON system_configurations(category);

-- ── 1. Slot Cutoff & Cron Timings ──────────────────────────────────────────
INSERT INTO system_configurations (config_key, category, name, description, config_data)
VALUES (
  'slot_timings',
  'timing',
  'Delivery Slots & Cron Execution Timings',
  'Cutoff times for customer ordering, automated cron run generation times, and dispatch windows for morning and evening slots.',
  jsonb_build_object(
    'morning_slot', jsonb_build_object(
      'slot_name', 'Morning',
      'slot_key', 'morning',
      'delivery_window_start', '06:00',
      'delivery_window_end', '08:30',
      'customer_cutoff_time', '20:00',
      'customer_cutoff_day_offset', -1,
      'customer_cutoff_description', '8:00 PM previous evening',
      'cron_run_time', '20:30',
      'cron_run_day_offset', -1,
      'cron_run_description', 'Runs at 8:30 PM previous evening to generate morning runs',
      'dispatch_start_time', '05:00',
      'is_enabled', true
    ),
    'evening_slot', jsonb_build_object(
      'slot_name', 'Evening',
      'slot_key', 'evening',
      'delivery_window_start', '17:00',
      'delivery_window_end', '20:00',
      'customer_cutoff_time', '14:00',
      'customer_cutoff_day_offset', 0,
      'customer_cutoff_description', '2:00 PM same day',
      'cron_run_time', '14:30',
      'cron_run_day_offset', 0,
      'cron_run_description', 'Runs at 2:30 PM same day to generate evening runs',
      'dispatch_start_time', '16:00',
      'is_enabled', true
    )
  )
)
ON CONFLICT (config_key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  config_data = system_configurations.config_data || EXCLUDED.config_data,
  updated_at = now();

-- ── 2. Background Automated Crons ──────────────────────────────────────────
INSERT INTO system_configurations (config_key, category, name, description, config_data)
VALUES (
  'cron_schedules',
  'cron',
  'Automated Background Cron Engines',
  'Scheduled crons for automated run generation, order routing, partner assignments, and payment reconciliation.',
  jsonb_build_object(
    'subscription_order_generator', jsonb_build_object(
      'name', 'Subscription Daily Order Generator',
      'is_enabled', true,
      'schedule_time', '03:30',
      'frequency', 'daily',
      'description', 'Generates recurring daily subscription order instances for active schedules.'
    ),
    'auto_run_creation', jsonb_build_object(
      'name', 'Automated Delivery Run Creation & Assignment',
      'is_enabled', true,
      'cron_expression', '0 4,14 * * *',
      'frequency', 'twice_daily',
      'description', 'Optimizes and assigns delivery routes to active delivery partners for upcoming morning & evening slots.'
    ),
    'payment_reconciliation_sweeper', jsonb_build_object(
      'name', 'Payment Reconciliation & Wallet Sweeper',
      'is_enabled', true,
      'cron_expression', '*/15 * * * *',
      'frequency', 'every_15_minutes',
      'description', 'Sweeps stranded online payments into customer wallets and reconciles pending gateway transactions.'
    ),
    'stranded_cart_cleaner', jsonb_build_object(
      'name', 'Abandoned Cart & Temporary Reservation Cleaner',
      'is_enabled', true,
      'cron_expression', '0 * * * *',
      'frequency', 'hourly',
      'description', 'Releases unconfirmed product reservations and cleans stale checkout sessions.'
    )
  )
)
ON CONFLICT (config_key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  config_data = system_configurations.config_data || EXCLUDED.config_data,
  updated_at = now();

-- ── 3. Delivery Charges & Fee Discount Rules ───────────────────────────────
INSERT INTO system_configurations (config_key, category, name, description, config_data)
VALUES (
  'delivery_rules',
  'pricing',
  'Delivery Fee & Discount Rules',
  'Standard delivery charges, free delivery thresholds, subscription waivers, and promotional rules.',
  jsonb_build_object(
    'base_delivery_fee', 39.00,
    'free_delivery_threshold', 199.00,
    'free_delivery_for_subscriptions', true,
    'free_delivery_first_order', true,
    'surge_fee_enabled', false,
    'surge_fee_amount', 0.00,
    'taxes_and_handling_fee', 0.00,
    'container_deposit_fee', 0.00,
    'currency', 'INR',
    'currency_symbol', '₹',
    'display_notes', 'Zero delivery fee on all active daily subscriptions. Standard delivery fee applies on single orders below ₹199.'
  )
)
ON CONFLICT (config_key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  config_data = system_configurations.config_data || EXCLUDED.config_data,
  updated_at = now();

-- ── 4. Customer Ordering Limits & Constraints ──────────────────────────────
INSERT INTO system_configurations (config_key, category, name, description, config_data)
VALUES (
  'order_rules',
  'ordering',
  'Customer Ordering Limits & Policies',
  'Minimum order value, advance ordering horizon, and subscription buffer limits.',
  jsonb_build_object(
    'min_order_subtotal', 40.00,
    'max_advance_days', 7,
    'auto_pause_subscription_low_balance', true,
    'subscription_advance_notice_hours', 12,
    'allow_instant_slot_switching', true
  )
)
ON CONFLICT (config_key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  config_data = system_configurations.config_data || EXCLUDED.config_data,
  updated_at = now();

COMMIT;
