CREATE TABLE "users" (
  "id" bigint  DEFAULT NULL,
  "sno" int  DEFAULT NULL,
  "user_id" VARCHAR(30)   NOT NULL,
  "email" text,
  "user_name" VARCHAR(30)   DEFAULT NULL,
  "password" VARCHAR(255)   DEFAULT NULL,
  "role_id" VARCHAR(30);
  "first_name" text,
  "last_name" text,
  "phone" text,
  "profile" VARCHAR(225)   DEFAULT NULL,
  "colors" VARCHAR(243) DEFAULT NULL,
  "cover" VARCHAR(30)   DEFAULT NULL,
  "settings" TEXT  ,
  "email_verified_at" timestamp NULL DEFAULT NULL,
  "password_changed_at" timestamp NULL DEFAULT NULL,
  "locked_at" timestamp NULL DEFAULT NULL,
  "fcm" text  ,
  "otp" int DEFAULT NULL,
  "last_login_at" timestamp NULL DEFAULT NULL,
  "session_token" text  ,
  "session_timeout" VARCHAR(200) DEFAULT NULL,
  "session_warning" VARCHAR(200) DEFAULT NULL,
  "refreshToken" text  ,
  "refreshTokenJti" VARCHAR(255)   DEFAULT NULL,
  "tokenRotationTracking" VARCHAR(255) DEFAULT NULL,
  "account_status" VARCHAR(30)   NOT NULL DEFAULT 'active',
  "max_logins" int DEFAULT NULL,
  "created_by" VARCHAR(30)   DEFAULT NULL,
  "updated_by" VARCHAR(250)   DEFAULT NULL,
  "delete_on" TIMESTAMP DEFAULT NULL,
  "restored_at" TIMESTAMP DEFAULT NULL,
  "deleted_at" TIMESTAMP DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  "must_change_password" SMALLINT NOT NULL DEFAULT '0'
);
CREATE CONSTRAINT fk_customer_user
FOREIGN KEY (user_id)
REFERENCES users(user_id);