// ============================================================================
// ChronoSparkSolutions — A Software Company
// © 2026 ChronoSparkSolutions. All rights reserved.
//
// Project     : F2H Fresh
// File        : system-config.service.ts
// Description : Service for managing developer system configurations & rules
// ============================================================================

import { Injectable, OnModuleInit, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../../shared/database/Database.service';
import { DeveloperService } from '../../shared/logger/Developer.service';
import { UpdateSystemConfigDto } from './system-config.dto';

export interface SlotTimingSlot {
  slot_name: string;
  slot_key: string;
  delivery_window_start: string;
  delivery_window_end: string;
  customer_cutoff_time: string;
  customer_cutoff_day_offset: number;
  customer_cutoff_description?: string;
  cron_run_time: string;
  cron_run_day_offset: number;
  cron_run_description?: string;
  dispatch_start_time: string;
  is_enabled: boolean;
}

export interface DeliveryFeeRules {
  base_delivery_fee: number;
  free_delivery_threshold: number;
  free_delivery_for_subscriptions: boolean;
  free_delivery_first_order: boolean;
  surge_fee_enabled: boolean;
  surge_fee_amount: number;
  taxes_and_handling_fee: number;
  container_deposit_fee: number;
  currency: string;
  currency_symbol: string;
  display_notes?: string;
}

@Injectable()
export class SystemConfigService implements OnModuleInit {
  constructor(
    private readonly db: DatabaseService,
    private readonly developer: DeveloperService,
  ) {}

  async onModuleInit() {
    await this.ensureSchema();
  }

  /**
   * Ensures the system_configurations table and default entries exist.
   */
  private async ensureSchema(): Promise<void> {
    try {
      await this.db.query(`
        CREATE TABLE IF NOT EXISTS system_configurations (
          id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          config_key   varchar(60) NOT NULL UNIQUE,
          category     varchar(40) NOT NULL DEFAULT 'system',
          name         varchar(100) NOT NULL,
          description  text,
          config_data  jsonb NOT NULL DEFAULT '{}'::jsonb,
          is_active    boolean NOT NULL DEFAULT true,
          updated_by   varchar(50),
          created_at   timestamptz DEFAULT now(),
          updated_at   timestamptz DEFAULT now(),
          deleted_at   timestamp
        );
        CREATE INDEX IF NOT EXISTS idx_system_configurations_key ON system_configurations(config_key);
        CREATE INDEX IF NOT EXISTS idx_system_configurations_category ON system_configurations(category);
      `);

      // Seed default configs if missing
      await this.seedDefaultsIfMissing();
    } catch (err) {
      this.developer.error('Failed to initialize system_configurations table', { error: err });
    }
  }

  private async seedDefaultsIfMissing(): Promise<void> {
    const existing = await this.db.query(`SELECT config_key FROM system_configurations`);
    const existingKeys = new Set((existing || []).map((r: any) => r.config_key));

    if (!existingKeys.has('slot_timings')) {
      await this.db.query(
        `INSERT INTO system_configurations (config_key, category, name, description, config_data)
         VALUES ($1, $2, $3, $4, $5)`,
        [
          'slot_timings',
          'timing',
          'Delivery Slots & Cron Execution Timings',
          'Cutoff times for customer ordering, automated cron run generation times, and dispatch windows for morning and evening slots.',
          JSON.stringify({
            morning_slot: {
              slot_name: 'Morning',
              slot_key: 'morning',
              delivery_window_start: '06:00',
              delivery_window_end: '08:30',
              customer_cutoff_time: '20:00',
              customer_cutoff_day_offset: -1,
              customer_cutoff_description: '8:00 PM previous evening',
              cron_run_time: '20:30',
              cron_run_day_offset: -1,
              cron_run_description: 'Runs at 8:30 PM previous evening to generate morning runs',
              dispatch_start_time: '05:00',
              is_enabled: true,
            },
            evening_slot: {
              slot_name: 'Evening',
              slot_key: 'evening',
              delivery_window_start: '17:00',
              delivery_window_end: '20:00',
              customer_cutoff_time: '14:00',
              customer_cutoff_day_offset: 0,
              customer_cutoff_description: '2:00 PM same day',
              cron_run_time: '14:30',
              cron_run_day_offset: 0,
              cron_run_description: 'Runs at 2:30 PM same day to generate evening runs',
              dispatch_start_time: '16:00',
              is_enabled: true,
            },
          }),
        ],
      );
    }

    if (!existingKeys.has('cron_schedules')) {
      await this.db.query(
        `INSERT INTO system_configurations (config_key, category, name, description, config_data)
         VALUES ($1, $2, $3, $4, $5)`,
        [
          'cron_schedules',
          'cron',
          'Automated Background Cron Engines',
          'Scheduled crons for automated run generation, order routing, partner assignments, and payment reconciliation.',
          JSON.stringify({
            subscription_order_generator: {
              name: 'Subscription Daily Order Generator',
              is_enabled: true,
              schedule_time: '03:30',
              frequency: 'daily',
              description: 'Generates recurring daily subscription order instances for active schedules.',
            },
            auto_run_creation: {
              name: 'Automated Delivery Run Creation & Assignment',
              is_enabled: true,
              cron_expression: '0 4,14 * * *',
              frequency: 'twice_daily',
              description: 'Optimizes and assigns delivery routes to active delivery partners for upcoming morning & evening slots.',
            },
            payment_reconciliation_sweeper: {
              name: 'Payment Reconciliation & Wallet Sweeper',
              is_enabled: true,
              cron_expression: '*/15 * * * *',
              frequency: 'every_15_minutes',
              description: 'Sweeps stranded online payments into customer wallets and reconciles pending gateway transactions.',
            },
            stranded_cart_cleaner: {
              name: 'Abandoned Cart & Temporary Reservation Cleaner',
              is_enabled: true,
              cron_expression: '0 * * * *',
              frequency: 'hourly',
              description: 'Releases unconfirmed product reservations and cleans stale checkout sessions.',
            },
          }),
        ],
      );
    }

    if (!existingKeys.has('delivery_rules')) {
      await this.db.query(
        `INSERT INTO system_configurations (config_key, category, name, description, config_data)
         VALUES ($1, $2, $3, $4, $5)`,
        [
          'delivery_rules',
          'pricing',
          'Delivery Fee & Discount Rules',
          'Standard delivery charges, free delivery thresholds, subscription waivers, and promotional rules.',
          JSON.stringify({
            base_delivery_fee: 39.0,
            free_delivery_threshold: 199.0,
            free_delivery_for_subscriptions: true,
            free_delivery_first_order: true,
            surge_fee_enabled: false,
            surge_fee_amount: 0.0,
            taxes_and_handling_fee: 0.0,
            container_deposit_fee: 0.0,
            currency: 'INR',
            currency_symbol: '₹',
            display_notes:
              'Zero delivery fee on all active daily subscriptions. Standard delivery fee applies on single orders below ₹199.',
          }),
        ],
      );
    }

    if (!existingKeys.has('order_rules')) {
      await this.db.query(
        `INSERT INTO system_configurations (config_key, category, name, description, config_data)
         VALUES ($1, $2, $3, $4, $5)`,
        [
          'order_rules',
          'ordering',
          'Customer Ordering Limits & Policies',
          'Minimum order value, advance ordering horizon, and subscription buffer limits.',
          JSON.stringify({
            min_order_subtotal: 40.0,
            max_advance_days: 7,
            auto_pause_subscription_low_balance: true,
            subscription_advance_notice_hours: 12,
            allow_instant_slot_switching: true,
          }),
        ],
      );
    }
  }

  /**
   * Retrieves all system configurations.
   */
  async getAllConfigs() {
    try {
      const rows = await this.db.query(`
        SELECT id, config_key, category, name, description, config_data, is_active, updated_by, updated_at
        FROM system_configurations
        WHERE deleted_at IS NULL
        ORDER BY id ASC;
      `);

      const configMap: Record<string, any> = {};
      for (const row of rows || []) {
        configMap[row.config_key] = {
          id: row.id,
          config_key: row.config_key,
          category: row.category,
          name: row.name,
          description: row.description,
          config_data: row.config_data,
          is_active: row.is_active,
          updated_by: row.updated_by,
          updated_at: row.updated_at,
        };
      }

      return {
        status: true,
        data: configMap,
        list: rows || [],
      };
    } catch (error) {
      this.developer.error('Error fetching system configurations', { error });
      return { status: false, message: 'Failed to fetch configurations', data: {}, list: [] };
    }
  }

  /**
   * Retrieves a single configuration by its key.
   */
  async getConfigByKey(configKey: string) {
    try {
      const rows = await this.db.query(
        `SELECT id, config_key, category, name, description, config_data, is_active, updated_by, updated_at
         FROM system_configurations
         WHERE config_key = $1 AND deleted_at IS NULL
         LIMIT 1`,
        [configKey],
      );

      if (!rows?.length) {
        throw new NotFoundException(`Configuration '${configKey}' not found`);
      }

      return {
        status: true,
        data: rows[0],
      };
    } catch (error) {
      this.developer.error(`Error fetching config ${configKey}`, { error });
      throw error;
    }
  }

  /**
   * Updates or creates a system configuration section.
   */
  async updateConfig(configKey: string, dto: UpdateSystemConfigDto, updatedBy?: string) {
    try {
      const existing = await this.db.query(
        `SELECT id, config_data FROM system_configurations WHERE config_key = $1 AND deleted_at IS NULL LIMIT 1`,
        [configKey],
      );

      let result;
      if (existing?.length) {
        const mergedData = {
          ...(existing[0].config_data || {}),
          ...dto.config_data,
        };

        const res = await this.db.query(
          `UPDATE system_configurations
           SET config_data = $1,
               name = COALESCE($2, name),
               description = COALESCE($3, description),
               is_active = COALESCE($4, is_active),
               updated_by = $5,
               updated_at = NOW()
           WHERE config_key = $6
           RETURNING id, config_key, category, name, description, config_data, is_active, updated_by, updated_at`,
          [
            JSON.stringify(mergedData),
            dto.name ?? null,
            dto.description ?? null,
            dto.is_active ?? null,
            updatedBy || 'admin',
            configKey,
          ],
        );
        result = res?.[0];
      } else {
        const res = await this.db.query(
          `INSERT INTO system_configurations (config_key, name, description, config_data, is_active, updated_by)
           VALUES ($1, $2, $3, $4, $5, $6)
           RETURNING id, config_key, category, name, description, config_data, is_active, updated_by, updated_at`,
          [
            configKey,
            dto.name || configKey,
            dto.description || '',
            JSON.stringify(dto.config_data),
            dto.is_active !== false,
            updatedBy || 'admin',
          ],
        );
        result = res?.[0];
      }

      this.developer.info(`System configuration '${configKey}' updated by ${updatedBy || 'admin'}`);

      return {
        status: true,
        message: `Configuration '${configKey}' updated successfully`,
        data: result,
      };
    } catch (error) {
      this.developer.error(`Error updating configuration ${configKey}`, { error });
      throw error;
    }
  }

  /**
   * Returns public client configurations for checkout and customer ordering.
   */
  async getPublicConfig() {
    try {
      const all = await this.getAllConfigs();
      const data = all.data || {};

      const deliveryRules: DeliveryFeeRules = data.delivery_rules?.config_data || {
        base_delivery_fee: 39.0,
        free_delivery_threshold: 199.0,
        free_delivery_for_subscriptions: true,
        free_delivery_first_order: true,
        surge_fee_enabled: false,
        surge_fee_amount: 0.0,
        taxes_and_handling_fee: 0.0,
        container_deposit_fee: 0.0,
        currency: 'INR',
        currency_symbol: '₹',
      };

      const slotTimings = data.slot_timings?.config_data || {};
      const orderRules = data.order_rules?.config_data || {};

      return {
        status: true,
        data: {
          delivery_rules: deliveryRules,
          slot_timings: slotTimings,
          order_rules: orderRules,
        },
      };
    } catch (error) {
      this.developer.error('Error fetching public config', { error });
      return {
        status: true,
        data: {
          delivery_rules: {
            base_delivery_fee: 39.0,
            free_delivery_threshold: 199.0,
            free_delivery_for_subscriptions: true,
            free_delivery_first_order: true,
            taxes_and_handling_fee: 0.0,
            currency: 'INR',
            currency_symbol: '₹',
          },
          slot_timings: {},
          order_rules: {
            min_order_subtotal: 40.0,
            max_advance_days: 7,
          },
        },
      };
    }
  }
}
