"use client";

import Link from "next/link";
import { ChevronRight, Home } from "lucide-react";

type Definition = {
  term: string;
  body: string;
};

type SubSection = {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
};

type TermsSection = {
  id: string;
  title: string;
  paragraphs?: string[];
  bullets?: string[];
  definitions?: Definition[];
  subsections?: SubSection[];
  note?: string;
};

const sections: TermsSection[] = [
  {
    id: "about-f2h",
    title: "1. About F2H",
    paragraphs: [
      "F2H - Farm to Home home delivers fresh milk and dairy products, along with ghee, curd, paneer, kova, carrot halwa, cold-pressed oils, and dry fruits, to customers' doorsteps every morning and evening. Select specialty items are curated from trusted local partners.",
      'F2H - Farm to Home ("F2H", "Company", "We", "Our", or "Us"), having its registered office at 1st Cross, SJP Layout, Nagondanahalli, Whitefield, Bangalore - 560066, Karnataka, India, owns and operates the website, mobile application, and any sub-domains thereof (collectively, the "Platform").',
      'For the purpose of these Terms and Conditions, wherever the context so requires, "You", "Your", or "User" refers to the natural or legal person, including the Buyer/Customer, who accesses and/or uses the Platform in any manner, and the term "Company", "F2H", "We", "Our", or "Us" shall mean F2H - Farm to Home.',
    ],
  },
  {
    id: "agreement-eligibility",
    title: "2. Agreement Between You and the Company, and Your Eligibility",
    paragraphs: [
      "These terms and conditions (\"Terms and Conditions\" or \"T&Cs\") are issued by the Company. Please read these T&Cs and Our Privacy Policy carefully before You start to use the Platform. By using and/or accessing this Platform, including all content available through it, You signify Your agreement to these T&Cs, the disclaimers, and the Privacy Policy as posted on the Platform, which are incorporated herein by reference. You may refrain from using this Platform if the same is not acceptable to You.",
      "You represent and warrant that You are competent and eligible to enter into a legally binding agreement and have the requisite authority and capacity to be bound by this Agreement. The Platform is not available to persons under the age of 18 (eighteen) years. If You are under the age of 18 years, You shall use and access the Platform only with the express consent of a parent or guardian and under their supervision.",
      'This document is an electronic record in terms of the Information Technology Act, 2000 (including all applicable rules framed thereunder) and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signature; however, once You have clicked the "I Accept" button on the Platform, You shall be deemed to have affixed Your signature to these T&Cs and granted Your consent to be bound by them.',
    ],
  },
  {
    id: "definitions",
    title: "3. Definitions",
    definitions: [
      {
        term: '"Agreement"',
        body: "means these Terms and Conditions as detailed herein, including all schedules, appendices, annexures, and the Privacy Policy, and includes references to this Agreement as amended, supplemented, varied, or replaced from time to time.",
      },
      {
        term: '"Applicable Law"',
        body: "means any national, regional, or local act, law, legislation, statute, rule, regulation, ordinance, decree, notification, policy, by-law, administrative guideline, ruling, instruction, directive, code, technical code, requirement, consent, licence, approval, permit, judgment, court order, treaty, or any interpretation thereof by any Government Authority applicable to the Company for owning and operating the Platform, including but not limited to the Information Technology Act, 2000, the Consumer Protection Act, 2019, the Digital Personal Data Protection Act, 2023, and the rules made thereunder.",
      },
      {
        term: '"Business Day"',
        body: "means the days on which banks remain open for business in India.",
      },
      {
        term: '"Platform" or "Site"',
        body: "means the F2H - Farm to Home website, mobile application, and sub-domains that provide a platform to shoppers to buy the products listed and avail the Services.",
      },
      {
        term: '"Customer"/"Buyer"',
        body: "means the person or legal entity who accepts the offer for sale on the Platform by placing an order for, and/or purchasing, any Products and/or availing any Services offered for sale on the Platform.",
      },
      {
        term: '"Intellectual Property Rights"',
        body: "means all data, information, inventions, intellectual property (including patents, trademarks, copyrights, designs, and trade secrets), know-how, new uses and processes, and any other intellectual property right, asset, or form — including analytical methods, procedures, techniques, research, procedure manuals, financial information, computer technical expertise, and software — related to or pertaining to the Services and Platform, whether pre-existing or conceived, generated, derived, produced, or reduced to practice by the Company or its affiliates, which shall remain the exclusive property of the Company (or its affiliates) unless otherwise stated in writing.",
      },
    ],
  },
  {
    id: "modification",
    title: "4. Modification of T&Cs",
    paragraphs: [
      "This Agreement is published in accordance with the provisions of Rule 3 of the Information Technology (Intermediaries Guidelines) Rules, 2011. We may change these T&Cs at any time without advance notice. Changed terms will become effective once posted on the Platform and will not have retrospective effect on existing contractual arrangements made through the Platform.",
      "You should regularly review these Terms and Conditions prior to using the Platform. If the modified Terms and Conditions are not acceptable to You, You should discontinue using the Platform. If You continue to use the Platform after any modification, You agree to accept and abide by the modified Terms and Conditions.",
    ],
  },
  {
    id: "term",
    title: "5. Term",
    paragraphs: [
      "This Agreement shall continue to be in full force and effect for as long as You are using the Platform.",
    ],
  },
  {
    id: "products-services-overview",
    title: "6. Products and Services Overview",
    paragraphs: [
      'The Platform provides an online shopping platform ("Services") through which Users can purchase Products listed on it, pursuant to these Terms and Conditions. Buyers/Customers can choose and place orders for milk, ghee, curd, paneer, kova, carrot halwa, cold-pressed oils, dry fruits, and other Products listed and offered for sale by the Company. Products and Services on the Platform are available only in select geographies in India and are subject to restrictions based on business hours, days, and availability of such Products and Services in such geographies.',
      "By clicking on the Payment option button, You agree to use the Services in a manner consistent with, and abide by, the Terms and Conditions of this Agreement, Our Privacy Policy, and all Applicable Laws.",
    ],
  },
  {
    id: "termination",
    title: "7. Termination",
    paragraphs: [
      "Either You or the Company may terminate this Agreement at any time, with or without cause. The Company reserves the right, in its sole discretion, to terminate Your access to the Platform (including access to Products and Services or any portion thereof) at any time, without notice.",
    ],
    bullets: [
      "It is discovered or brought to notice that You do not conform to the eligibility criteria;",
      "The Company has reason to believe (including through evaluating usage patterns) that the eligibility criteria are not met or are violated by a User, or that the User is incapable of contracting;",
      "The Company is required to do so by law (for example, where the provision of Services to You is, or becomes, unlawful); or",
      "You breach any provision of this Agreement, or have acted in a manner that clearly shows You do not intend to, or are unable to, comply with the same.",
    ],
  },
  {
    id: "shipping-delivery",
    title: "8. Terms of Shipping and Delivery",
    paragraphs: [
      "You agree and undertake that You are accessing the Services and transacting at Your sole risk, and are using Your best and prudent judgment before entering into any transaction on the Platform.",
      "The Company operates two dedicated delivery shifts every day — Morning Shift (5:30 AM to 7:30 AM) and Evening Shift (5:00 PM to 7:30 PM). After recharge of Your prepaid wallet or activation of an approved postpaid credit limit, the Company arranges for doorstep delivery of the ordered Products to Your designated address in the applicable shift.",
      "Money for a scheduled delivery is deducted from Your F2H wallet only upon generation and dispatch of the delivery manifest. You are responsible for reviewing quantities and product selections before cut-off times. Any order placed or scheduled on active subscription is a firm commitment to purchase.",
      "While the Company strives to deliver Products to every residential community within active zones, serviceability is confirmed by route logistics. If an address is determined to be unserviceable, 100% of any remaining real-currency wallet balance will be refunded immediately to Your original payment source.",
      "Customers are required to hang a clean, reusable F2H insulated bag outside their door for silent morning drops. The Company's delivery partners will place the items securely in the bag and log photo confirmation.",
      "The Company maintains a strict cold-chain process (2°C to 6°C) from collection at the dairy farm to doorstep arrival.",
    ],
  },
  {
    id: "pricing",
    title: "9. Pricing and Tax Inclusivity",
    paragraphs: [
      "All product prices listed on the Platform and in product catalog tables are 100% inclusive of all applicable Goods & Services Tax (GST). There are zero separate delivery, handling, or surge fees for active scheduled subscriptions.",
      "Due to the perishable nature of fresh farm milk and seasonal dairy commodities, prices may be adjusted from time to time. Any price revision will be updated transparently on the Platform and applied to future recurring subscription cycles with advance notice.",
      "If the Company cancels a delivery shift due to extreme weather or unserviceability, You will not be charged, and the corresponding amount will be credited back to Your F2H wallet within 2 hours or refunded to Your bank source in 5-7 working days.",
    ],
  },
  {
    id: "membership",
    title: "10. Membership, Offers & Cashback",
    paragraphs: [
      "F2H Membership is a discount programme on the F2H mobile application that allows users to avail discounts on Products at prices lower than both the listed MRP and the prices offered to non-member users. The discount offered, and the maximum discount available, varies from plan to plan and can only be availed while shopping on the F2H mobile application.",
    ],
    bullets: [
      "A user can become a member only via the F2H mobile application, and membership pricing and discounts can be changed by F2H at its own discretion.",
      "F2H reserves the right to offer or showcase Membership at its own discretion, and to terminate a Membership plan at any point.",
      "Membership cannot be cancelled, transferred, or encashed. Leftover benefit amount from a previous membership will be carried forward on renewal made before expiry.",
      "Membership discounts cannot be clubbed with any other discount or cashback offer, and Users must have sufficient Membership benefit available to avail a discount on any Product.",
      "In case of auto-renewal, the membership renews one day prior to expiry, with unused benefits carried over; if the wallet is insufficient or the account has a vacation marked, auto-renewal will be disabled at the time of renewal.",
      "F2H shall not be liable for misdirected, delayed, or inaccurate credits arising from information provided by the User. Unlimited-benefit plans are subject to a Fair Usage Policy defined by F2H.",
      "If a user is on auto-renewal for an Unlimited Benefit plan and savings at expiry are less than the amount paid, F2H will refund the difference to the wallet; this applies only to auto-renewed Unlimited Benefit plans.",
      "F2H reserves the right to withhold discounts, debit already-credited bonuses in case of any violation of these Terms, and to modify or amend Membership benefits or these Terms at any time, including disqualifying any user from Membership at its sole discretion.",
      "Users can pause their Membership plan up to 2 times, for up to 15 days per pause, per Membership cycle; F2H may modify the number or duration of pauses at its discretion.",
      "The user agrees to indemnify, release, and hold harmless F2H from any claims, losses, or liabilities arising out of or related to enrollment in the Membership plan.",
      "Membership programmes, offers, and cashbacks are optional and may be changed at any time without prior notice; Products remain available on the Platform without such membership. Only one offer is applicable per address, and F2H may withdraw an offer if it discovers multiple redemptions at the same address.",
      "Cashback credited in relation to AutoPay activation or transactions is conditional on the AutoPay mandate remaining active; if the mandate is cancelled, disabled, or becomes inactive for any reason, F2H reserves the right to reverse, recover, or adjust the cashback previously credited.",
    ],
  },
  {
    id: "user-obligations",
    title: "11. User Obligations",
    paragraphs: [
      "Subject to compliance with these T&Cs, the Company grants You a personal, non-exclusive, non-transferable, limited privilege to access and use the Platform and the Services provided herein.",
      "You agree to use the Platform only for purposes permitted by these T&Cs and applicable law, and to adhere to all limitations on dissemination, use, and reproduction of any materials You access on the Platform. You shall not access, or attempt to access, the Platform other than through the interface provided by the Company, and shall not use any data scraper, deep-link, robot, spider, or other automated means to access, acquire, copy, or monitor any portion of the Platform or its content.",
      "Purchases made through the Platform are strictly for personal consumption and not for any commercial purpose. You shall not purchase Products for resale, trade, distribution, stockpiling, or other commercial or profit-oriented activity without the Company's prior written authorisation. Any such unauthorised use may result in appropriate legal action, including civil and/or criminal proceedings.",
    ],
  },
  {
    id: "cancellation-policy",
    title: "12. Cancellation Policy",
    bullets: [
      "The Customer can cancel or stop their subscription using the Platform or by reaching out to customer support.",
      "A Customer will not create multiple accounts at the same address. If this is found, the Company has the right to cancel or merge the accounts and/or cancel the subscription.",
    ],
  },
  {
    id: "fresh-dairy-refusal",
    title: "13. Refusal of Fresh Dairy Products at Delivery",
    paragraphs: [
      'Milk, curd, and other fresh dairy Products are prepared and packed specifically for Your delivery shift. If a Customer denies taking delivery of such a Product at the time of delivery, they will be required to pay a Product Loss Charge of INR 100 (or such other amount as may be indicated on the Platform from time to time). This charge is levied only to cover the loss to the Company for processing and preparing the delivery in compliance with Applicable Law, and is agreed to be a genuine pre-estimate of loss rather than a penalty.',
    ],
  },
  {
    id: "reviews-feedback",
    title: "14. Reviews and Feedback",
    paragraphs: [
      'All reviews, comments, feedback, suggestions, ideas, and other submissions disclosed, submitted, or offered on the Platform (collectively, "Comments") shall remain the property of the Company. The Company may use, reproduce, disclose, modify, delete, adapt, create derivative works from, publish, display, and distribute any Comments for any purpose whatsoever, without restriction and without compensating the User.',
      "Reliance placed on Comments from a third party is at the sole risk and expense of the User. Comments may be left at support@f2hfresh.com. Comments must not be libellous, unlawful, threatening, abusive, obscene, contain viruses, political campaigning, commercial solicitation, chain letters, or spam. The Company reserves the right, but assumes no obligation, to moderate or delete any Comments.",
    ],
  },
  {
    id: "entire-agreement",
    title: "15. Entire Agreement",
    paragraphs: [
      "These Terms and Conditions, together with the Privacy Policy and other rules and policies posted on the Platform, constitute the entire agreement between You and the Company with respect to Your use of the Platform, and supersede all prior or contemporaneous communications and proposals. Any rights not expressly granted herein are reserved.",
      "If any provision of these Terms and Conditions is found to be unlawful, invalid, or unenforceable, that provision (or part thereof) shall be deemed not to form part of these Terms and Conditions, and the legality, validity, and enforceability of the remaining provisions shall not be affected. The invalid provision shall be replaced by one that is legal, valid, and enforceable, and that has, to the greatest extent possible, a similar effect.",
    ],
  },
  {
    id: "communication",
    title: "16. Communication",
    paragraphs: [
      "By registering with F2H, You permit Us to send You notifications via WhatsApp, Your registered mobile number, email, push notifications, customer support calls, the App, and the Website — regarding orders placed by You, promotional offers, and product recommendations. You may opt out of promotional notifications on WhatsApp, Your registered mobile number, and email by contacting customer care at support@f2hfresh.com.",
    ],
  },
  {
    id: "intellectual-property",
    title: "17. Intellectual Property Rights",
    paragraphs: [
      "The Platform, and its processes, selection, and arrangement — including all text, videos, graphics, user interfaces, visual interfaces, sounds, music, artwork, and computer code (and any combination thereof) — belong to the Company. The design, structure, selection, coordination, expression, look and feel, and arrangement of such content is protected by copyright, patent, trademark, and other Intellectual Property laws.",
      'The trademarks, logos, and service marks displayed on the Platform ("Marks") are the property of the Company or third parties. You are not permitted to use the Marks without the Company\'s prior consent. Access to or use of the Platform does not authorise use of any trademark, logo, or other mark.',
      "You acknowledge that the Company is the sole and rightful owner of its Intellectual Property, and agree not to register, use, or file, in Your own name or that of any other person or company, any trademark that is the same as, similar to, or resembles the Company's Intellectual Property, and not to associate the Company's Intellectual Property with Your own business except as specified in these Terms. Intellectual Property rights arising from domain names, the internet, or otherwise shall vest in the Company as the owner of such domain name.",
      "References on the Platform to any name, mark, service, or product of third parties are provided with the express consent of such third party for Your convenience, and do not constitute an endorsement, sponsorship, recommendation, assurance, or warranty of such services or Products.",
    ],
  },
  {
    id: "billing-payment",
    title: "18. Billing Policy, Wallets & Payment Gateways",
    paragraphs: [
      "The Platform supports secure online payments via Razorpay payment gateway, supporting UPI (Google Pay, PhonePe, Paytm), Credit Cards, Debit Cards, NetBanking, and recurring AutoPay / e-Mandates.",
      "Prepaid Wallet: Customers maintain an in-app F2H Wallet balance for daily auto-debits. Money is deducted only upon generation of the active delivery manifest for that shift.",
      "Postpaid Accounts: Approved postpaid enterprise and residential customers receive an itemized monthly billing statement with detailed tax breakdown. Invoices are payable within 7 calendar days of statement generation.",
    ],
    bullets: [
      "A complete summary of daily deliveries and wallet transactions is accessible on the Platform for instant review and PDF statement download.",
      "All card transactions are processed through PCI-DSS certified encryption gateways. The Company does not store raw credit card numbers or CVV codes.",
      "Customers can initiate wallet top-ups starting at INR 200 via any supported online payment mode.",
    ],
  },
  {
    id: "return-policy",
    title: "19. Return, Quality & 2-Hour Wallet Refund Policy",
    paragraphs: [
      "Orders for the Morning Shift must be placed, modified, or cancelled by 9:00 PM the previous night. Orders for the Evening Shift must be placed, modified, or cancelled by 10:00 AM the same day. Cancellations made prior to the respective cut-off are 100% free of charge.",
      "Given the perishable nature of fresh farm milk, physical returns are not accepted once delivered. However, for any verified quality defect (such as curdling upon boil or packaging damage):",
    ],
    bullets: [
      "Quality issues with fresh milk, curd, or paneer must be reported via the app or WhatsApp within 24 hours of delivery with photo proof.",
      "Quality issues with ghee, oils, or dry fruits must be reported within 3 days (72 hours) of delivery.",
      "2-Hour Wallet Refund: Verified claims are credited back to Your F2H Wallet within 2 hours.",
      "Original Source Bank Refund: Refunds requested back to the original bank account or payment card upon account closure are processed via Razorpay within 5-7 working days.",
    ],
  },
  {
    id: "referral-program",
    title: "20. F2H Referral Program",
    bullets: [
      "One user can refer a maximum of 15 new users. The Referee and the Referrer cannot share the same address.",
      "The Referrer must have made at least one recharge with F2H in the last 30 days of a minimum value of INR 150, or a cumulative lifetime wallet recharge of INR 2,000 or more.",
      "To count as a successful referral, the Referee must complete at least one wallet recharge of a minimum value of INR 200.",
      "The Referrer receives 100% cashback, up to a maximum of INR 100 per Referee, on the Referee's first qualifying wallet recharge. F2H reserves the right to revise the maximum cashback percentage or amount at any time.",
      "Referral bonuses cannot be clubbed with any other promotional offer or bonus. The bonus amount credited to a wallet can be used only for purchases on the F2H Platform, is non-transferable, and cannot be exchanged for cash under any circumstances.",
      "F2H reserves the right to modify or amend these Terms and to disqualify any Referrer from participation at any time, at its sole discretion, including for non-compliance with these Terms.",
      "The Referrer and Referee agree to indemnify, release, and hold harmless F2H from any claims, losses, or liabilities arising out of or related to their participation in the referral programme.",
      "No person under 18 years of age may use, access, or participate in the referral programme at any time or in any manner.",
      "F2H shall not be liable for late, delayed, stolen, misdirected, or inaccurate credits arising from information provided by the Referee or Referrer, and reserves the right to hold back or debit an already-credited referral bonus in case of any violation of these Terms.",
    ],
  },
  {
    id: "nach-mandate",
    title: "21. NACH Mandate and Transaction Management",
    paragraphs: [
      "Transactions against a NACH Mandate are processed only on a Business Day; a transaction due on a non-Business Day will be processed on the next Business Day. If a transaction fails, it will not be retried for that calendar month. Customers cannot modify an existing NACH Mandate, as this modification flow is not presently supported by banks, but may revoke a mandate at least two days prior to the next Due Date and set up a new one.",
      "Processing of a NACH Mandate is subject to the actions of the destination bank and clearance of funds by that bank. Upon revocation of a mandate at the Customer's request, the Customer must reinitiate the entire process to set up a new mandate. F2H shall not be liable for transactions processed due to a Customer's failure to revoke a mandate within the required window, and such transactions shall constitute valid and binding transactions on the Customer.",
      "F2H processes a NACH Mandate solely on the basis of the destination account details provided by the Customer and verified by the destination bank, and is not responsible for independently verifying those details.",
    ],
    bullets: [
      "The Company assumes no liability if it is unable to process a transaction against a NACH Mandate because the mandate is incomplete, inaccurate, invalid, or incorrect;",
      "The destination account has insufficient balance to cover the mandated amount;",
      "Funds in the destination account are under any encumbrance, charge, or the destination bank's right of lien; or",
      "The destination account is under any attachment or debit freeze pursuant to legal or regulatory direction.",
    ],
  },
  {
    id: "prepaid-products",
    title: "22. Pre-paid Products & AutoPay Wallet Maintenance",
    paragraphs: [
      "To activate a daily recurring subscription, You are required to top-up Your F2H wallet with a minimum initial recharge of INR 200. You may also activate Razorpay AutoPay for automatic wallet replenishment when Your balance dips below INR 100.",
    ],
  },
  {
    id: "grievance-redressal",
    title: "23. Grievance Redressal Mechanism",
    paragraphs: [
      "Protecting the interests of Users is a primary objective of the Company. A grievance redressal cell has been set up to deal with all queries, complaints, or grievances raised by Users, in accordance with the Information Technology Act, 2000, the Information Technology (Intermediaries Guidelines) Rules, 2011, the Consumer Protection Act, 2019 read with the Consumer Protection (E-Commerce) Rules, 2020, and applicable national data privacy laws.",
      "The Company shall only be responsible for addressing claims from You or any third party relating to the Platform, or Your possession and/or use of the Platform, subject to a maximum of the value of the Products purchased by You from the Platform.",
      "All complaints to the Grievance Officer must be in writing, in English, and sent to the email address below. The Grievance Officer shall acknowledge or respond within 48 hours of receipt, and shall aim to redress the complaint within 1 month of receipt.",
    ],
    subsections: [
      {
        title: "Grievance Officer",
        bullets: [
          "Email: grievanceofficer@f2hfresh.com",
          "Primary phone: +91 91487 73591",
          "Secondary phone: +91 79893 68142",
        ],
      },
      {
        title: "Nodal Officer",
        bullets: [
          "Email: nodal@f2hfresh.com",
        ],
      },
    ],
  },
  {
    id: "protection-of-data",
    title: "24. Protection of Your Data",
    paragraphs: [
      "Any information provided by You for purchasing Products will not be retained by the Company except as provided in these Terms and Conditions and the Privacy Policy. Such information may be transferred to third-party service providers, in accordance with the Privacy Policy, to facilitate Your purchase of Products from the Platform. The collection, storage, retention, use, and disclosure of personal information is subject to the Privacy Policy available on the Platform, which governs Your visit to and use of the Platform and forms an integral part of these Terms and Conditions.",
    ],
  },
  {
    id: "relationship",
    title: "25. Relationship",
    paragraphs: [
      "It is understood that the parties to these Terms and Conditions have confirmed their acceptance on a principal-to-principal basis. These Terms and Conditions do not create any agency, partnership, joint venture, or similar relationship between the parties.",
    ],
  },
  {
    id: "indemnification",
    title: "26. Indemnification",
    paragraphs: [
      "You agree to defend, indemnify, and hold harmless the Company, its employees, directors, officers, agents, and their successors and assigns from and against any claims, liabilities, damages, losses, costs, and expenses (including attorney's fees) arising out of a breach of any warranty, representation, or undertaking in this Agreement, or a violation of Applicable Law — including in relation to intellectual property rights, statutory dues and taxes, claims of libel or defamation, violation of privacy or publicity rights, loss of service by other subscribers, and infringement of intellectual property or other rights. This clause shall survive the expiry or termination of this Agreement.",
    ],
    bullets: [
      "Except as required by Applicable Law, the Company is not liable for payments authorised through the Platform using Your payment details, including where a payment fails to complete because Your account had insufficient funds, You provided incorrect payment details, Your payment card had expired, or due to circumstances beyond the Company's reasonable control (such as power outages or interruptions of cellular service).",
      "The Company shall be under no liability for any loss or damage arising from the decline of authorisation for a transaction on account of the cardholder exceeding a limit agreed between the Company and its acquiring bank.",
      "The Company shall in no case be liable for indirect losses, loss of profits, or incidental, punitive, or consequential damages caused to Customers.",
      "Any difference between a representational image and the actual Product is for advertorial purposes only.",
    ],
  },
  {
    id: "medical-emergency-disclaimer",
    title: "27. Medical Emergency Disclaimer",
    paragraphs: [
      "The Company does not provide emergency medical services or medical assistance of any kind. While the Company takes reasonable steps for the timely delivery of Products, the Customer agrees that the Company shall not be held liable for any medical emergency, including injury, harm, or life-threatening condition, arising directly or indirectly from delivery, non-delivery, or short-delivery of a Product purchased from the Platform. Customers are solely responsible for ordering desired Products well in advance, and for seeking immediate medical assistance from qualified emergency service providers in the event of a medical emergency.",
    ],
  },
  {
    id: "governing-law",
    title: "28. Governing Law and Jurisdiction",
    paragraphs: [
      "These Terms and Conditions shall be governed by and interpreted in accordance with the laws of India. Subject to applicable consumer protection law and mandatory statutory rights, the courts at Bangalore, Karnataka shall have exclusive jurisdiction to try any dispute arising out of or related to these Terms and Conditions.",
    ],
  },
  {
    id: "contact",
    title: "29. Contact Us",
    paragraphs: [
      "For questions, support, complaints, or notices related to these Terms, You may contact F2H using the details below.",
    ],
    subsections: [
      {
        title: "Customer and grievance contact",
        bullets: [
          "Email: support@f2hfresh.com",
          "Primary phone: +91 91487 73591",
          "Secondary phone: +91 79893 68142",
          "WhatsApp: Message us on WhatsApp via the number listed on the Platform",
          "Delivery shifts: Morning & Evening, every day",
          "Registered office: 1st Cross, SJP Layout, Nagondanahalli, Whitefield, Bangalore - 560066, Karnataka, India",
          "Turnaround time: Within 48 hours of acknowledgment, and expeditious redressal within 1 month, or within the time required under applicable law.",
        ],
      },
    ],
  },
];

function renderBullets(items?: string[], sectionNumber?: string) {
  if (!items?.length) return null;

  return (
    <ul className="mt-3 space-y-3">
      {items.map((item, i) => (
        <li key={item} className="flex gap-2.5 text-[13px] leading-6 text-slate-600 sm:text-sm">
          <span className="shrink-0 font-semibold text-slate-500">
            {sectionNumber}.{i + 1}
          </span>
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );
}

function renderParagraphs(items?: string[], sectionNumber?: string) {
  if (!items?.length) return null;

  return (
    <div className="space-y-3">
      {items.map((item, i) => (
        <p key={item} className="flex gap-2.5 text-[13px] leading-6 text-slate-600 sm:text-sm">
          <span className="shrink-0 font-semibold text-slate-500">
            {sectionNumber}.{i + 1}
          </span>
          <span>{item}</span>
        </p>
      ))}
    </div>
  );
}

export default function TermsAndConditionsPage() {
  return (
    <div className="min-h-screen bg-[#f7faf8]" style={{ fontFamily: "Poppins, sans-serif" }}>
      <div className="mx-auto max-w-[1240px] px-3 pb-14 pt-28 sm:px-4 lg:px-5">
        <nav className="mb-5 flex items-center gap-1.5 text-sm text-slate-500">
          <Link href="/" className="flex items-center gap-1 transition-colors hover:text-emerald-700">
            <Home size={14} />
            Home
          </Link>
          <ChevronRight size={14} className="text-slate-300" />
          <span className="font-semibold text-slate-800">Terms & Conditions</span>
        </nav>

        <article className="rounded-[8px] border border-slate-200 bg-white px-4 py-7 shadow-sm sm:px-6 lg:px-7">
          <div className="mb-8 border-b border-slate-100 pb-6">
            <p className="mb-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-emerald-700">
              F2H - Farm to Home
            </p>
            <h1 className="text-2xl font-bold tracking-normal text-slate-950 sm:text-[28px]">
              Terms & Conditions
            </h1>
          </div>

          <div className="space-y-7">
            {sections.map((section, index) => {
              const [sectionNumber, ...sectionTitleParts] = section.title.split(". ");
              const sectionTitle = sectionTitleParts.join(". ");

              return (
                <section
                  key={section.id}
                  id={section.id}
                  className={`scroll-mt-28 ${index === 0 ? "" : "border-t border-slate-100 pt-7"}`}
                >
                  <div className="mb-3 flex items-start gap-3">
                    <span className="flex h-7 min-w-7 items-center justify-center rounded-full bg-emerald-50 text-[13px] font-bold text-emerald-700 ring-1 ring-emerald-100">
                      {sectionNumber}
                    </span>
                    <h2 className="pt-0.5 text-[15px] font-bold leading-6 tracking-normal text-slate-950 sm:text-base">
                      {sectionTitle}
                    </h2>
                  </div>

                  <div className="ml-10 border-l border-emerald-100 pl-4">
                    {renderParagraphs(section.paragraphs, sectionNumber)}
                    {renderBullets(section.bullets, sectionNumber)}

                    {section.definitions?.length ? (
                      <ul className="mt-3 space-y-3">
                        {section.definitions.map((definition) => (
                          <li key={definition.term} className="text-[13px] leading-6 text-slate-600 sm:text-sm">
                            <span className="font-semibold text-slate-900">{definition.term}</span>{" "}
                            {definition.body}
                          </li>
                        ))}
                      </ul>
                    ) : null}

                    {section.subsections?.map((subsection) => (
                      <div key={subsection.title} className="mt-4 rounded-[8px] border border-slate-100 bg-slate-50/80 p-4">
                        <h3 className="mb-2 text-sm font-semibold text-slate-900">
                          {subsection.title}
                        </h3>
                        {renderParagraphs(subsection.paragraphs, sectionNumber)}
                        {renderBullets(subsection.bullets, sectionNumber)}
                      </div>
                    ))}

                    {section.note ? (
                      <p className="mt-4 rounded-[8px] border border-emerald-100 bg-emerald-50 px-4 py-3 text-[13px] font-medium leading-6 text-emerald-900 shadow-[inset_3px_0_0_0_rgba(5,150,105,0.35)] sm:text-sm">
                        {section.note}
                      </p>
                    ) : null}
                  </div>
                </section>
              );
            })}
          </div>
        </article>
      </div>
    </div>
  );
}