android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=false

# JVM Arguments: Expanded for Gradle transforms & Kotlin compilation
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC
kotlin.daemon.jvm.options=-Xmx1024m -XX:+UseG1GC

# Limit parallel execution
org.gradle.workers.max=2
org.gradle.parallel=false

# Flutter migrator flags
android.builtInKotlin=false
android.newDsl=false
